all destroy

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,7 +20,7 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Configure AWS credentials from AWS account
-        uses: aws-actions/configure-aws-credentials@v1
+        uses: aws-actions/configure-aws-credentials@v4
         with:
           role-to-assume: ${{ secrets.AWS_GITHUB_OIDC_ARN }}
           role-session-name: ${{ secrets.AWS_OIDC_SESSION_NAME }}
@@ -50,73 +50,73 @@ jobs:
           -backend-config="key=${AWS_BUCKET_KEY_NAME}" 
           -backend-config="region=${AWS_REGION}"
 
-      # - name: Terraform Destroy
-      #   id: destroy
+      - name: Terraform Destroy
+        id: destroy
+        working-directory: ./terraform
+        env:
+          AWS_REGION: ${{ secrets.AWS_REGION }}
+        run: terraform destroy -auto-approve
+
+      # - name: Terraform Validate
+      #   id: validate
+      #   run: terraform validate -no-color
       #   working-directory: ./terraform
+      #
+      # - name: Terraform Plan
+      #   id: plan
+      #   working-directory: ./terraform
+      #   run: terraform plan -no-color
+      #   if: github.event_name == 'pull_request'
+      #
+      # - name: Terraform Run
+      #   id: run
+      #   uses: actions/github-script@v7
+      #   if: github.event_name == 'pull_request'
       #   env:
-      #     AWS_REGION: ${{ secrets.AWS_REGION }}
-      #   run: terraform destroy -auto-approve
-
-      - name: Terraform Validate
-        id: validate
-        run: terraform validate -no-color
-        working-directory: ./terraform
-
-      - name: Terraform Plan
-        id: plan
-        working-directory: ./terraform
-        run: terraform plan -no-color
-        if: github.event_name == 'pull_request'
-
-      - name: Terraform Run
-        id: run
-        uses: actions/github-script@v7
-        if: github.event_name == 'pull_request'
-        env:
-          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-        with:
-          working-directory: ./terraform
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-            <details><summary>Validation Output</summary>
-            \`\`\`\n
-            ${{ steps.validate.outputs.stdout }}
-            \`\`\`
-
-            </details>
-
-            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-
-            <details><summary>Show Plan</summary>
-
-            \`\`\`\n
-            ${process.env.PLAN}
-            \`\`\`
-
-            </details>
-
-            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
-
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
-
-      - name: Terraform Plan Status
-        id: status
-        working-directory: ./terraform
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
-
-      - name: Terraform Apply
-        id: apply
-        working-directory: ./terraform
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: terraform apply -auto-approve -input=false
-        env:
-          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
+      #     PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+      #   with:
+      #     working-directory: ./terraform
+      #     github-token: ${{ secrets.GITHUB_TOKEN }}
+      #     script: |
+      #       const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+      #       #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+      #       #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+      #       <details><summary>Validation Output</summary>
+      #       \`\`\`\n
+      #       ${{ steps.validate.outputs.stdout }}
+      #       \`\`\`
+      #
+      #       </details>
+      #
+      #       #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+      #
+      #       <details><summary>Show Plan</summary>
+      #
+      #       \`\`\`\n
+      #       ${process.env.PLAN}
+      #       \`\`\`
+      #
+      #       </details>
+      #
+      #       *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+      #
+      #       github.rest.issues.createComment({
+      #         issue_number: context.issue.number,
+      #         owner: context.repo.owner,
+      #         repo: context.repo.repo,
+      #         body: output
+      #       })
+      #
+      # - name: Terraform Plan Status
+      #   id: status
+      #   working-directory: ./terraform
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
+      #
+      # - name: Terraform Apply
+      #   id: apply
+      #   working-directory: ./terraform
+      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+      #   run: terraform apply -auto-approve -input=false
+      #   env:
+      #     TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
